name: Build Windows

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8.15.4
          run_install: false

      - name: Install nexe
        run: pnpm install -g nexe@next

      - name: Install dependencies
        run: pnpm install

      - name: Build Tunarr
        run: pnpm turbo bundle

      - name: Build Windows exe
        run: pnpm turbo make-exec:windows
