name: Build Windows

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          file: ./docker/nexe-windows.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
