on:
  workflow_dispatch:
  push:
    branches:
      - dev

permissions:
  contents: write
  pull-requests: write

name: Create Release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
